name: Arch Linux Build Test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Arch Linux build test
      uses: ./actions/build-test-arch/
