name: PR Checks

on:
  pull_request:
    branches:
      - master

jobs:
  # Make sure downstream packages still build and install
  build-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Arch Linux build test
      uses: ./actions/build-test-arch/
