name: PR Checks

on:
  pull_request:
    branches:
      - master

jobs:
  # Make sure downstream packages still build and install
  arch-build-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Arch Linux build test
      uses: ./actions/build-test-arch/
  rpm-build-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fedora-version: ['fc43', 'fc42', 'fc41']
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Dockerfile for Fedora ${{ matrix.fedora-version }}
      run: |
        cp -v ./actions/build-test-rpm/Dockerfile.${{ matrix.fedora-version }} ./actions/build-test-rpm/Dockerfile
    - name: RPM build test
      uses: ./actions/build-test-rpm/
      env:
        GSSMN_SOURCES: .
        GSSMN_SHA1: ${{ github.sha }}
